# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commitwindow.ui'
#
# Created: Sun Jun 19 14:03:37 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CommitWindow(object):
    def setupUi(self, CommitWindow):
        CommitWindow.setObjectName("CommitWindow")
        CommitWindow.resize(919, 414)
        self.formLayoutWidget = QtGui.QWidget(CommitWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(14, 30, 341, 371))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txtDescription = QtGui.QTextBrowser(self.formLayoutWidget)
        self.txtDescription.setMinimumSize(QtCore.QSize(240, 0))
        self.txtDescription.setMaximumSize(QtCore.QSize(240, 16777215))
        self.txtDescription.setObjectName("txtDescription")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtDescription)
        self.txtHash = QtGui.QLineEdit(self.formLayoutWidget)
        self.txtHash.setMinimumSize(QtCore.QSize(240, 0))
        self.txtHash.setMaximumSize(QtCore.QSize(240, 16777215))
        self.txtHash.setReadOnly(True)
        self.txtHash.setObjectName("txtHash")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtHash)
        self.txtDate = QtGui.QLineEdit(self.formLayoutWidget)
        self.txtDate.setMinimumSize(QtCore.QSize(240, 0))
        self.txtDate.setMaximumSize(QtCore.QSize(240, 16777215))
        self.txtDate.setReadOnly(True)
        self.txtDate.setObjectName("txtDate")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtDate)
        self.txtTime = QtGui.QLineEdit(self.formLayoutWidget)
        self.txtTime.setMinimumSize(QtCore.QSize(240, 0))
        self.txtTime.setMaximumSize(QtCore.QSize(240, 16777215))
        self.txtTime.setReadOnly(True)
        self.txtTime.setObjectName("txtTime")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtTime)
        self.txtAuthor = QtGui.QLineEdit(self.formLayoutWidget)
        self.txtAuthor.setMinimumSize(QtCore.QSize(240, 0))
        self.txtAuthor.setMaximumSize(QtCore.QSize(240, 16777215))
        self.txtAuthor.setReadOnly(True)
        self.txtAuthor.setObjectName("txtAuthor")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtAuthor)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lblLinesAdded = QtGui.QLabel(self.formLayoutWidget)
        self.lblLinesAdded.setText("")
        self.lblLinesAdded.setObjectName("lblLinesAdded")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lblLinesAdded)
        self.lblLinesDeleted = QtGui.QLabel(self.formLayoutWidget)
        self.lblLinesDeleted.setText("")
        self.lblLinesDeleted.setObjectName("lblLinesDeleted")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lblLinesDeleted)
        self.treeFiles = QtGui.QTreeView(CommitWindow)
        self.treeFiles.setGeometry(QtCore.QRect(360, 30, 191, 371))
        self.treeFiles.setObjectName("treeFiles")
        self.label_6 = QtGui.QLabel(CommitWindow)
        self.label_6.setGeometry(QtCore.QRect(360, 10, 59, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(CommitWindow)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 59, 16))
        self.label_7.setObjectName("label_7")
        self.label_12 = QtGui.QLabel(CommitWindow)
        self.label_12.setGeometry(QtCore.QRect(560, 10, 81, 16))
        self.label_12.setObjectName("label_12")
        self.txtChanges = QtGui.QTextBrowser(CommitWindow)
        self.txtChanges.setGeometry(QtCore.QRect(560, 30, 351, 371))
        self.txtChanges.setObjectName("txtChanges")

        self.retranslateUi(CommitWindow)
        QtCore.QMetaObject.connectSlotsByName(CommitWindow)

    def retranslateUi(self, CommitWindow):
        CommitWindow.setWindowTitle(QtGui.QApplication.translate("CommitWindow", "Commit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CommitWindow", "Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CommitWindow", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CommitWindow", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CommitWindow", "Hash", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CommitWindow", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CommitWindow", "Lines added:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CommitWindow", "Lines deleted:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CommitWindow", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CommitWindow", "Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CommitWindow", "Changes:", None, QtGui.QApplication.UnicodeUTF8))

