# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jun 19 14:03:37 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(940, 680)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(940, 680))
        MainWindow.setMaximumSize(QtCore.QSize(940, 680))
        MainWindow.setBaseSize(QtCore.QSize(940, 680))
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 160, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.LeftMenu = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.LeftMenu.setContentsMargins(0, 0, 0, 0)
        self.LeftMenu.setObjectName("LeftMenu")
        self.lblBrs = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblBrs.setObjectName("lblBrs")
        self.LeftMenu.addWidget(self.lblBrs)
        self.brComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.brComboBox.setEnabled(False)
        self.brComboBox.setObjectName("brComboBox")
        self.LeftMenu.addWidget(self.brComboBox)
        self.lblDevs = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblDevs.setObjectName("lblDevs")
        self.LeftMenu.addWidget(self.lblDevs)
        self.devComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.devComboBox.setObjectName("devComboBox")
        self.LeftMenu.addWidget(self.devComboBox)
        self.lblStartDate = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblStartDate.setObjectName("lblStartDate")
        self.LeftMenu.addWidget(self.lblStartDate)
        self.startDateEdit = QtGui.QDateTimeEdit(self.verticalLayoutWidget)
        self.startDateEdit.setObjectName("startDateEdit")
        self.LeftMenu.addWidget(self.startDateEdit)
        self.lblEndDate = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblEndDate.setObjectName("lblEndDate")
        self.LeftMenu.addWidget(self.lblEndDate)
        self.endDateEdit = QtGui.QDateTimeEdit(self.verticalLayoutWidget)
        self.endDateEdit.setObjectName("endDateEdit")
        self.LeftMenu.addWidget(self.endDateEdit)
        self.btnVisualize = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnVisualize.setObjectName("btnVisualize")
        self.LeftMenu.addWidget(self.btnVisualize)
        self.btnReset = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnReset.setObjectName("btnReset")
        self.LeftMenu.addWidget(self.btnReset)
        self.lblMenu = QtGui.QLabel(self.centralWidget)
        self.lblMenu.setGeometry(QtCore.QRect(10, 70, 148, 20))
        self.lblMenu.setObjectName("lblMenu")
        self.activityView = QtGui.QGraphicsView(self.centralWidget)
        self.activityView.setGeometry(QtCore.QRect(10, 420, 920, 220))
        self.activityView.setMinimumSize(QtCore.QSize(920, 220))
        self.activityView.setMaximumSize(QtCore.QSize(920, 220))
        self.activityView.setObjectName("activityView")
        self.filesView = QtGui.QTreeView(self.centralWidget)
        self.filesView.setGeometry(QtCore.QRect(360, 90, 191, 321))
        self.filesView.setObjectName("filesView")
        self.commitsView = QtGui.QListView(self.centralWidget)
        self.commitsView.setGeometry(QtCore.QRect(180, 90, 171, 321))
        self.commitsView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.commitsView.setObjectName("commitsView")
        self.lblCommits = QtGui.QLabel(self.centralWidget)
        self.lblCommits.setGeometry(QtCore.QRect(180, 70, 148, 20))
        self.lblCommits.setObjectName("lblCommits")
        self.lblFiles = QtGui.QLabel(self.centralWidget)
        self.lblFiles.setGeometry(QtCore.QRect(360, 70, 148, 20))
        self.lblFiles.setObjectName("lblFiles")
        self.diffView = QtGui.QTextBrowser(self.centralWidget)
        self.diffView.setGeometry(QtCore.QRect(560, 90, 371, 321))
        self.diffView.setObjectName("diffView")
        self.lblChanges = QtGui.QLabel(self.centralWidget)
        self.lblChanges.setGeometry(QtCore.QRect(560, 70, 61, 16))
        self.lblChanges.setObjectName("lblChanges")
        self.btnOpenProject = QtGui.QPushButton(self.centralWidget)
        self.btnOpenProject.setGeometry(QtCore.QRect(0, 10, 113, 32))
        self.btnOpenProject.setObjectName("btnOpenProject")
        self.btnSaveDevs = QtGui.QPushButton(self.centralWidget)
        self.btnSaveDevs.setEnabled(False)
        self.btnSaveDevs.setGeometry(QtCore.QRect(110, 10, 151, 32))
        self.btnSaveDevs.setObjectName("btnSaveDevs")
        self.btnSearchCommit = QtGui.QPushButton(self.centralWidget)
        self.btnSearchCommit.setEnabled(False)
        self.btnSearchCommit.setGeometry(QtCore.QRect(260, 10, 151, 32))
        self.btnSearchCommit.setObjectName("btnSearchCommit")
        self.formLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(730, 10, 160, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.lineChangeLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.lineChangeLayout.setContentsMargins(0, 0, 0, 0)
        self.lineChangeLayout.setObjectName("lineChangeLayout")
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.lineChangeLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.lineChangeLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.lineChangeLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lblLinesAffected = QtGui.QLabel(self.formLayoutWidget)
        self.lblLinesAffected.setText("")
        self.lblLinesAffected.setObjectName("lblLinesAffected")
        self.lineChangeLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblLinesAffected)
        self.lblLinesAdded = QtGui.QLabel(self.formLayoutWidget)
        self.lblLinesAdded.setText("")
        self.lblLinesAdded.setObjectName("lblLinesAdded")
        self.lineChangeLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblLinesAdded)
        self.lblLinesDeleted = QtGui.QLabel(self.formLayoutWidget)
        self.lblLinesDeleted.setText("")
        self.lblLinesDeleted.setObjectName("lblLinesDeleted")
        self.lineChangeLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lblLinesDeleted)
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(410, 10, 321, 54))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.authorLayout = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.authorLayout.setContentsMargins(0, 0, 0, 0)
        self.authorLayout.setObjectName("authorLayout")
        self.lblEmail = QtGui.QLabel(self.formLayoutWidget_2)
        self.lblEmail.setObjectName("lblEmail")
        self.authorLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblEmail)
        self.lblAuthor = QtGui.QLabel(self.formLayoutWidget_2)
        self.lblAuthor.setObjectName("lblAuthor")
        self.authorLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblAuthor)
        self.editAuthor = QtGui.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editAuthor.sizePolicy().hasHeightForWidth())
        self.editAuthor.setSizePolicy(sizePolicy)
        self.editAuthor.setMinimumSize(QtCore.QSize(250, 0))
        self.editAuthor.setObjectName("editAuthor")
        self.authorLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.editAuthor)
        self.editEmail = QtGui.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editEmail.sizePolicy().hasHeightForWidth())
        self.editEmail.setSizePolicy(sizePolicy)
        self.editEmail.setMinimumSize(QtCore.QSize(250, 0))
        self.editEmail.setObjectName("editEmail")
        self.authorLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.editEmail)
        self.formLayoutWidget_3 = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 391, 23))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.commitLayout = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.commitLayout.setContentsMargins(0, 0, 0, 0)
        self.commitLayout.setObjectName("commitLayout")
        self.editCommit = QtGui.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editCommit.sizePolicy().hasHeightForWidth())
        self.editCommit.setSizePolicy(sizePolicy)
        self.editCommit.setMinimumSize(QtCore.QSize(320, 0))
        self.editCommit.setObjectName("editCommit")
        self.commitLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.editCommit)
        self.label = QtGui.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName("label")
        self.commitLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 940, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSearch = QtGui.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionLil = QtGui.QAction(MainWindow)
        self.actionLil.setObjectName("actionLil")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Project visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBrs.setText(QtGui.QApplication.translate("MainWindow", "Branches", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDevs.setText(QtGui.QApplication.translate("MainWindow", "Developers", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStartDate.setText(QtGui.QApplication.translate("MainWindow", "Start date:", None, QtGui.QApplication.UnicodeUTF8))
        self.startDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd.MM.yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("MainWindow", "End date:", None, QtGui.QApplication.UnicodeUTF8))
        self.endDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd.MM.yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVisualize.setText(QtGui.QApplication.translate("MainWindow", "Visualize", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMenu.setText(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCommits.setText(QtGui.QApplication.translate("MainWindow", "Commits", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFiles.setText(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.lblChanges.setText(QtGui.QApplication.translate("MainWindow", "Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenProject.setText(QtGui.QApplication.translate("MainWindow", "Open project", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveDevs.setText(QtGui.QApplication.translate("MainWindow", "Save developers info", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchCommit.setText(QtGui.QApplication.translate("MainWindow", "Search for commit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Lines affected:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Lines added:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Lines deleted:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("MainWindow", "Email:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAuthor.setText(QtGui.QApplication.translate("MainWindow", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Commit:", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save developers info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLil.setText(QtGui.QApplication.translate("MainWindow", "lil", None, QtGui.QApplication.UnicodeUTF8))

